# Get all books
GET http://localhost:3001/books HTTP/1.1 
Content-Type: application/json

###
# Add a book
POST http://localhost:3001/books HTTP/1.1 
Content-Type: application/json

{
  "title": "Prisoner of Azkaban"
}

###
# Update a book
PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{"title": "Light Tower"}

###
# Delete a book
DELETE http://localhost:3001/books/2 HTTP/1.1
Content-Type: application/json
